spring:
  profiles:
    active:
      - dev
---
server:
  port: 8888
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.springcloud: debug
    org.springframework.security: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true 
    service-url:
      defaultZone: http://admin:a@eureka1:7301/eureka #授信用户登录
  instance:
    prefer-ip-address: true 
    instance-id: base-microservice-provider-pics   #实例名
    lease-expiration-duration-in-seconds:  90 #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )

#监控配置
info:
  app.name: provider-pics
  company.name: yc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'
